# Generated by Django 4.2.8 on 2026-02-26 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador del Proyecto'), ('CONSULTANT', 'Consultor'), ('CLIENT', 'Cliente'), ('VIEWER', 'Observador')], max_length=20, verbose_name='Rol en el proyecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='projects.project', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario de Proyecto',
                'verbose_name_plural': 'Usuarios de Proyectos',
                'db_table': 'projects_projectuser',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
